/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.gaast.deoxide;

public final class R {
    public static final class array {
        public static final int block_schedule_element_sizes=0x7f040000;
        public static final int block_schedule_element_sizes_values=0x7f040001;
        public static final int default_view=0x7f040002;
        public static final int default_view_values=0x7f040003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int blockschedule=0x7f020000;
        public static final int deoxide_icon_48x48=0x7f020001;
        public static final int ic_menu_clock_face=0x7f020002;
        public static final int star_black=0x7f020003;
        public static final int star_yellow=0x7f020004;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int preferences=0x7f030000;
    }
}
