runtime: python313

inbound_services:
- warmup

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  static_files: index.html
  upload: index.html

- url: /_ah/warmup
  secure: optional
  script: auto

- url: /nodatapolicy.*
  secure: always
  redirect_http_response_code: 301
  static_files: nodatapolicy.html
  upload: nodatapolicy.html

- url: /.well-known/assetlinks.json
  secure: optional
  static_files: assetlinks.json
  upload: assetlinks.json

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  max_instances: 3
