runtime: python310

inbound_services:
- warmup

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  static_files: index.html
  upload: index.html

- url: /nodatapolicy.*
  secure: always
  redirect_http_response_code: 301
  static_files: nodatapolicy.html
  upload: nodatapolicy.html

- url: /_ah/warmup
  secure: optional
  script: auto

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
